default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: media_mingle_development

test:
  <<: *default
  database: media_mingle_test

production:
  <<: *default
  database: media_mingle_production
  username: media_mingle
  password: <%= ENV["MEDIA_MINGLE_DATABASE_PASSWORD"] %>
